name: UpperVoid_Serv
main: com.Geekpower14.UpperVoid.UpperVoid
version: 1.0.0
author: Geekpower14
website: http://geekpower14.com/
depend: [PermissionsEx]
commands:
   uv:
      description: UpperVoid Command
      aliases: [uv]